### ISSUE TITLE
Spatially resolved heatmaps 

### ISSUE THREAD

**Issue by MertDemirdizen** [Teichlab/limbcellatlas#1]
Hi, 
Congrats on the great work.
Sorry for using your respiratory for an unrelated thing but I wondered how you plot two genes on the same spatial map as in Figure 5. If you can show me, I would appreciate it. Thank you very much in advance.

**Comment by brianpenghe** [comment]
Dear Mert,

You can plot that by hijacking [cell2location's function to plot two cell abundances](https://cell2location.readthedocs.io/en/latest/notebooks/cell2location_tutorial.html#Visualising-cell-abundance-in-spatial-coordinates)

If you want to plot two genes, you can save the gene values to the .obs of the adata object pretending that they are cell abundance scores; and then plot those "scores".

Hope that makes sense?

![image](https://user-images.githubusercontent.com/4110443/172025451-f2a042aa-7dcc-4217-93a9-3f884050da71.png)

**Comment by MertDemirdizen** [comment]
Thank you very much,
It helped me a lot!

**Comment by brianpenghe** [comment]
Hello @MertDemirdizen , good news: we've now got a tool to do this. Please check this out: https://github.com/JPatrickPett/pseudo_rnascope.git
