### ISSUE TITLE
How to access data

### ISSUE THREAD

**Issue by GilbertHan1011** [Teichlab/limbcellatlas#2]
![2022-07-07_16-33](https://user-images.githubusercontent.com/39906045/177729440-2554518d-8f1e-468c-a0af-a5769d81aba6.png)
Hello, congratulations to your great work!

I try to access the [data website](https://limb-dev.cellgeni.sanger.ac.uk/). However, I don't know how to regist and login. Could you plese tell me how to access the processed data? It will be a great help.

I'd be more than grateful if you can help me.

**Comment by brianpenghe** [comment]
We have fixed this. Please check again?
