### ISSUE TITLE
Access to count data

### ISSUE THREAD

**Issue by MNStokholm** [Teichlab/limbcellatlas#3]
I downloaded the anndata objects from https://limb-dev.cellgeni.sanger.ac.uk/, but the object doesn't seem to include the count data. I've tried looking through all the relevant files, but couldn't find anything.

Please advice on how to access the count data for the human_all data.

**Comment by brianpenghe** [comment]
Hi Mathias,

Have you tried converting the log-transformed values to raw counts?
Code can be found here:
https://github.com/brianpenghe/python-genomics/blob/9a90aea58b9c2f43d688949524d02777723403de/Scanpyplus.py#L119

If you need pre-filtered one, I can email them to you.

**Comment by MNStokholm** [comment]
Thanks for the quick answer. A prefiltered one would be great. You can reach me here: mnstokholm@gmail.com

**Comment by brianpenghe** [comment]
Just shared it with you by Google Drive!
